-- Generated by Oracle SQL Developer Data Modeler 21.1.0.092.1221
--   at:        2022-07-06 18:11:14 BRT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



DROP TABLE t_cliente CASCADE CONSTRAINTS;

DROP TABLE t_contato_cliente CASCADE CONSTRAINTS;

DROP TABLE t_contrato CASCADE CONSTRAINTS;

DROP TABLE t_corretor CASCADE CONSTRAINTS;

DROP TABLE t_saude CASCADE CONSTRAINTS;

DROP TABLE t_seguro_vida CASCADE CONSTRAINTS;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE t_cliente (
    cd_cliente            NUMBER(5) NOT NULL,
    nm_cliente            VARCHAR2(100) NOT NULL,
    nr_cpf_cliente        VARCHAR2(14) NOT NULL,
    dt_nasc_cliente       DATE NOT NULL,
    ds_nacionali_cliente  VARCHAR2(60) NOT NULL,
    nr_rg_cliente         VARCHAR2(20) NOT NULL,
    sg_genero_cliente     CHAR(1) NOT NULL,
    ds_profi_cliente      VARCHAR2(100) NOT NULL,
    ds_est_civ_cliente    VARCHAR2(30) NOT NULL,
    vl_renda_cliente      NUMBER(7, 2) NOT NULL
);

COMMENT ON TABLE t_cliente IS
    'Tabela de Clientes da empresa Tokio Marine';

COMMENT ON COLUMN t_cliente.cd_cliente IS
    'Código do Cliente ';

COMMENT ON COLUMN t_cliente.nm_cliente IS
    'Nome do cliente';

COMMENT ON COLUMN t_cliente.nr_cpf_cliente IS
    'Número do CPF do cliente';

COMMENT ON COLUMN t_cliente.dt_nasc_cliente IS
    'Data de nascimento do cliente';

COMMENT ON COLUMN t_cliente.ds_nacionali_cliente IS
    'Nacionalidade do cliente';

COMMENT ON COLUMN t_cliente.nr_rg_cliente IS
    'Número do RG do cliente';

COMMENT ON COLUMN t_cliente.sg_genero_cliente IS
    'Sigla do genêro do cliente';

COMMENT ON COLUMN t_cliente.ds_profi_cliente IS
    'Profissão do Cliente';

COMMENT ON COLUMN t_cliente.ds_est_civ_cliente IS
    'Estado civil do cliente';

COMMENT ON COLUMN t_cliente.vl_renda_cliente IS
    'Renda fixa do cliente para analisar com os valores dos seguros';

ALTER TABLE t_cliente ADD CONSTRAINT t_cliente_pk PRIMARY KEY ( cd_cliente );

CREATE TABLE t_contato_cliente (
    cd_contato_cliente      NUMBER(5) NOT NULL,
    ds_email_cliente        VARCHAR2(100) NOT NULL,
    nr_cel_cliente          NUMBER(11) NOT NULL,
    nr_tel_cliente          VARCHAR2(13),
    nm_rua_cliente          VARCHAR2(130) NOT NULL,
    nr_moradia_cliente      NUMBER(6) NOT NULL,
    nr_cep_cliente          VARCHAR2(15) NOT NULL,
    ds_complemento_cliente  VARCHAR2(160) NOT NULL,
    nm_bairro_cliente       VARCHAR2(60) NOT NULL,
    nm_cidade_cliente       VARCHAR2(100) NOT NULL,
    nm_estado_cliente       VARCHAR2(60) NOT NULL,
    cd_cliente              NUMBER(5) NOT NULL
);

COMMENT ON TABLE t_contato_cliente IS
    'Tabela de Contato ao cliente da empresa Tokio Marine';

COMMENT ON COLUMN t_contato_cliente.cd_contato_cliente IS
    'Código de contado ao cliente';

COMMENT ON COLUMN t_contato_cliente.ds_email_cliente IS
    'Email de contato de cliente';

COMMENT ON COLUMN t_contato_cliente.nr_cel_cliente IS
    'Número do celular do cliente';

COMMENT ON COLUMN t_contato_cliente.nr_tel_cliente IS
    'Número de telefone do cliente';

COMMENT ON COLUMN t_contato_cliente.nm_rua_cliente IS
    'Nome da rua do cliente';

COMMENT ON COLUMN t_contato_cliente.nr_moradia_cliente IS
    'Número da moradia do cliente ';

COMMENT ON COLUMN t_contato_cliente.nr_cep_cliente IS
    'Número do CEP do cliente';

COMMENT ON COLUMN t_contato_cliente.ds_complemento_cliente IS
    'Complemento do endereço da moradia do cliente';

COMMENT ON COLUMN t_contato_cliente.nm_bairro_cliente IS
    'Nome do bairro da moradia do cliente';

COMMENT ON COLUMN t_contato_cliente.nm_cidade_cliente IS
    'Nome da cidade onde cliente mora';

COMMENT ON COLUMN t_contato_cliente.nm_estado_cliente IS
    'Nome do estado do cliente';

CREATE UNIQUE INDEX t_contato_cliente__idx ON
    t_contato_cliente (
        cd_cliente
    ASC );

ALTER TABLE t_contato_cliente ADD CONSTRAINT t_contato_cliente_pk PRIMARY KEY ( cd_contato_cliente,
                                                                                cd_cliente );

CREATE TABLE t_contrato (
    cd_contrato         NUMBER(5) NOT NULL,
    ds_ass_cliente      VARCHAR2(80) NOT NULL,
    ds_ass_corretor     VARCHAR2(80),
    dt_inicio_contrato  DATE NOT NULL,
    dt_fim_contrato     DATE,
    cd_cliente          NUMBER(5) NOT NULL,
    cd_corretor         NUMBER(5) NOT NULL,
    cd_seguro_vida      NUMBER(5) NOT NULL
);

COMMENT ON TABLE t_contrato IS
    'Contrato do cliente com o corretor.';

COMMENT ON COLUMN t_contrato.cd_contrato IS
    'Codigo do contrato.';

COMMENT ON COLUMN t_contrato.ds_ass_cliente IS
    'Assinatura do cliente.';

COMMENT ON COLUMN t_contrato.ds_ass_corretor IS
    'Assinatura do corretor.';

COMMENT ON COLUMN t_contrato.dt_inicio_contrato IS
    'Data do inicio do contrato.';

COMMENT ON COLUMN t_contrato.dt_fim_contrato IS
    'Data do termino do contrato.';

CREATE UNIQUE INDEX t_contrato__idx ON
    t_contrato (
        cd_cliente
    ASC );

ALTER TABLE t_contrato ADD CONSTRAINT t_contrato_pk PRIMARY KEY ( cd_contrato );

CREATE TABLE t_corretor (
    cd_corretor          NUMBER(5) NOT NULL,
    nm_corretor          VARCHAR2(60) NOT NULL,
    tp_pessoa_corretor   VARCHAR2(100) NOT NULL,
    nr_cpf_corretor      VARCHAR2(60) NOT NULL,
    cd_susep_corretor    NUMBER(5) NOT NULL,
    ds_email_corretor    VARCHAR2(100) NOT NULL,
    nr_tel_corretor      VARCHAR2(11) NOT NULL,
    vl_salario_corretor  NUMBER(7, 2) NOT NULL
);

COMMENT ON TABLE t_corretor IS
    'Tabela de corretor da empresa Tokio Marine';

COMMENT ON COLUMN t_corretor.cd_corretor IS
    'Código do corretor';

COMMENT ON COLUMN t_corretor.nm_corretor IS
    'Nome do corretor';

COMMENT ON COLUMN t_corretor.tp_pessoa_corretor IS
    'Tipo de pessoa do corretor';

COMMENT ON COLUMN t_corretor.nr_cpf_corretor IS
    'Número do CPF/CNPJ do corretor';

COMMENT ON COLUMN t_corretor.cd_susep_corretor IS
    'código susep/ibracor do corretor';

COMMENT ON COLUMN t_corretor.ds_email_corretor IS
    'Email do corretor';

COMMENT ON COLUMN t_corretor.nr_tel_corretor IS
    'Número do telefone do corretor';

COMMENT ON COLUMN t_corretor.vl_salario_corretor IS
    'Salario do corretor.';

ALTER TABLE t_corretor ADD CONSTRAINT t_corretor_pk PRIMARY KEY ( cd_corretor );

CREATE TABLE t_saude (
    cd_saude_cliente     NUMBER(5) NOT NULL,
    nm_assegurado_saude  VARCHAR2(80),
    ds_esp_rad_cliente   VARCHAR2(60),
    ds_doenca_cliente    VARCHAR2(60),
    sg_vicio_cliente     CHAR(1),
    cd_cliente           NUMBER(5) NOT NULL
);

COMMENT ON TABLE t_saude IS
    'Tabela de dados da saúde do cliente';

COMMENT ON COLUMN t_saude.cd_saude_cliente IS
    'Código da saúde do cliente
';

COMMENT ON COLUMN t_saude.nm_assegurado_saude IS
    'Nome da pessoa com algum problema de saude';

COMMENT ON COLUMN t_saude.ds_esp_rad_cliente IS
    'Se o cliente prática algum esporte radical';

COMMENT ON COLUMN t_saude.ds_doenca_cliente IS
    'Se o cliente tem alguma doença';

COMMENT ON COLUMN t_saude.sg_vicio_cliente IS
    'Se o cliente possui algum vicio.';

ALTER TABLE t_saude ADD CONSTRAINT t_saude_pk PRIMARY KEY ( cd_saude_cliente,
                                                            cd_cliente );

CREATE TABLE t_seguro_vida (
    cd_seguro_vida  NUMBER(5) NOT NULL,
    vl_seguro_vida  NUMBER(7, 2) NOT NULL,
    nm_seguro_vida  VARCHAR2(400) NOT NULL,
    ds_cobertura    VARCHAR2(400) NOT NULL
);

COMMENT ON TABLE t_seguro_vida IS
    'Tabela reunião de seguros de vida';

COMMENT ON COLUMN t_seguro_vida.cd_seguro_vida IS
    'Código do seguro de vida';

COMMENT ON COLUMN t_seguro_vida.vl_seguro_vida IS
    'Valor deste seguro de vida';

COMMENT ON COLUMN t_seguro_vida.nm_seguro_vida IS
    'Descrição do seguro de vida.';

COMMENT ON COLUMN t_seguro_vida.ds_cobertura IS
    'Cobertura do seguro.';

ALTER TABLE t_seguro_vida ADD CONSTRAINT t_seguro_vida_pk PRIMARY KEY ( cd_seguro_vida );

ALTER TABLE t_contato_cliente
    ADD CONSTRAINT fk_cliente_contato FOREIGN KEY ( cd_cliente )
        REFERENCES t_cliente ( cd_cliente );

ALTER TABLE t_saude
    ADD CONSTRAINT fk_cliente_saude FOREIGN KEY ( cd_cliente )
        REFERENCES t_cliente ( cd_cliente );

ALTER TABLE t_contrato
    ADD CONSTRAINT fk_corretor_contrato FOREIGN KEY ( cd_corretor )
        REFERENCES t_corretor ( cd_corretor );

ALTER TABLE t_contrato
    ADD CONSTRAINT fk_seguro_contrato FOREIGN KEY ( cd_seguro_vida )
        REFERENCES t_seguro_vida ( cd_seguro_vida );

ALTER TABLE t_contrato
    ADD CONSTRAINT tk_cliente_contrato FOREIGN KEY ( cd_cliente )
        REFERENCES t_cliente ( cd_cliente );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             6
-- CREATE INDEX                             2
-- ALTER TABLE                             11
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
